name: Build Padavan Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git-core libncurses5-dev unzip gawk zlib1g-dev libssl-dev gettext xsltproc libxml-parser-perl wget help2man libtool-bin

    - name: Verify libtool installation
      run: |
        libtool --version
        which libtool

    - name: Clone Padavan repository
      run: |
        git clone https://gitlab.com/dm38/padavan-ng.git padavan
        cd padavan
        git checkout master
        git submodule update --init --recursive

    - name: List available configuration files
      run: |
        cd padavan/trunk
        ls -R configs/templates/tplink

    - name: Set up toolchain
      run: |
        cd padavan/toolchain

    - name: Configure build
      run: |
        cd padavan/trunk
        ./clear_tree.sh
        ls -l configs/templates/tplink/tl_wr845n-v4.config  # Debug: Verify config file exists
        cp configs/templates/tplink/tl_wr845n-v4.config .config
        ls -l .config  # Debug: Verify .config file was copied
        echo 'CONFIG_FIRMWARE_INCLUDE_LANG_EN=y' >> .config
        cat .config  # Debug: Display contents of .config

    - name: Build firmware
      run: |
        cd padavan/trunk
        fakeroot ./build_firmware.sh

    - name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: padavan-firmware
        path: |
          padavan/trunk/images/*.bin
