name: Build Padavan Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git-core libncurses5-dev unzip gawk zlib1g-dev libssl-dev gettext xsltproc libxml-parser-perl wget help2man libtool-bin automake autoconf m4 perl

        # Create symlinks for aclocal-1.15 if needed
        if [ ! -f /usr/bin/aclocal-1.15 ]; then
          sudo ln -s /usr/bin/aclocal /usr/bin/aclocal-1.15
        fi
        if [ ! -f /usr/bin/automake-1.15 ]; then
          sudo ln -s /usr/bin/automake /usr/bin/automake-1.15
        fi

    - name: Verify tool installation
      run: |
        libtool --version
        which libtool
        automake --version
        aclocal --version

    - name: Clone Padavan repository
      run: |
        git clone https://gitlab.com/dm38/padavan-ng.git padavan
        cd padavan
        git checkout master
        git submodule update --init --recursive

    - name: List available configuration files
      run: |
        cd padavan/trunk
        ls -R configs/templates/tplink

    - name: Copy and modify configuration file
      run: |
        cd padavan/trunk
        ls -l configs/templates/tplink/tl_wr845n-v4.config  # Verify config file exists
        cp configs/templates/tplink/tl_wr845n-v4.config .config || { echo "Failed to copy config file"; exit 1; }
        ls -l .config  # Verify .config file was copied
        echo 'CONFIG_FIRMWARE_INCLUDE_LANG_UK=y' >> .config || { echo "Failed to append to .config"; exit 1; }
        sed -i 's/^CONFIG_FIRMWARE_INCLUDE_LANG_RU/# CONFIG_FIRMWARE_INCLUDE_LANG_RU/' .config || { echo "Failed to comment out CONFIG_FIRMWARE_INCLUDE_LANG_RU"; exit 1; }
        cat .config  # Display contents of .config

    - name: Set up toolchain
      run: |
        cd padavan/toolchain
        ./clean_sources.sh
        ./build_toolchain.sh

    - name: Configure build
      run: |
        cd padavan/trunk
        ./clear_tree.sh

    - name: Build firmware
      run: |
        cd padavan/trunk
        fakeroot ./build_firmware.sh

    - name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: padavan-firmware
        path: |
          padavan/trunk/images/*.bin
