name: Build Padavan Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git-core libncurses5-dev unzip gawk zlib1g-dev libssl-dev gettext xsltproc libxml-parser-perl wget help2man libtool-bin

        # Add libtool path to PATH
        echo "export PATH=\$PATH:/usr/bin" >> $GITHUB_ENV

    - name: Verify libtool installation
      run: |
        /usr/bin/libtool --version
        which libtool

    - name: Clone Padavan repository
      run: |
        git clone https://gitlab.com/dm38/padavan-ng.git padavan
        cd padavan
        git checkout master
        git submodule update --init --recursive

    - name: Set up toolchain
      run: |
        cd padavan/toolchain
        ./clean_sources.sh
        ./build_toolchain.sh

    - name: Configure build
      run: |
        cd padavan/trunk
        ./clear_tree.sh
        cp configs/templates/TL-WR845N.config .config
        echo 'CONFIG_FIRMWARE_INCLUDE_LANG_EN=y' >> .config

    - name: Build firmware
      run: |
        cd padavan/trunk
        fakeroot ./build_firmware.sh

    - name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: padavan-firmware
        path: |
          padavan/trunk/images/*.bin
